#!/bin/sh
#
# chkconfig:   - 20 80
# description: Starts and stops mailcatcher

# Source function library.
. /etc/rc.d/init.d/functions

name="mailcatcher"
exec="/usr/bin/$name"
lockfile="/var/lock/subsys/$name"

start() {
    [ -x $exec ] || exit 5
    echo -n $"Starting $name: "
    daemon "$exec --http-ip 0.0.0.0"
    retval=$?
    echo
    [ $retval -eq 0 ] && touch $lockfile
    return $retval
}

stop() {
    echo -n $"Stopping $name: "
    killall $name
    retval=$?
    echo
    [ $retval -eq 0 ] && rm -f $lockfile
    return $retval
}

restart() {
    stop
    start
}

reload() {
    false
}

rh_status() {
    if [ $(ps ax | grep mailcatcher | grep ruby | grep -v grep | wc -l) -gt 0 ]
    then
        return 0
    else
        return 1
    fi
}

rh_status_q() {
    rh_status >/dev/null 2>&1
}


case "$1" in
    start)
        rh_status_q && exit 0
        $1
        ;;
    stop)
        rh_status_q || exit 0
        $1
        ;;
    restart)
        $1
        ;;
    reload)
        rh_status_q || exit 7
        $1
        ;;
    force-reload)
        force_reload
        ;;
    status)
        rh_status
        ;;
    condrestart|try-restart)
        rh_status_q || exit 0
        restart
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart|condrestart|try-restart}"
        exit 2
esac
exit $?
